modLoader="javafml"
loaderVersion="[47,)"
license="MIT license"

[[mods]]
modId="risus"
version="1.20.1-0.0.1"
displayName="Risus"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Thanks to my friends in Trailblazers' Pantheon for forcing me to make a mod and Twig_Demon for constant feedback"
authors="bigdious"
description='''
A mod to make you smile.'''

[[dependencies.risus]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.risus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
