modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="risus"
version="1.16.5-0.0.1"
displayName="Risus"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Thanks to my friends in Trailblazers' Pantheon for forcing me to make a mod and Twig_Demon for constant feedback"
authors="bigdious"
description='''
A mod to make you smile.'''

[[dependencies.risus]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.risus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
