modLoader="javafml"
loaderVersion="[1,)"
license="MIT license"

[[mods]]
modId="risus"
version="${file.jarVersion}"
displayName="Risus"
logoFile="examplemod.png"
credits="Thanks to my friends in Trailblazers' Pantheon for forcing me to make a mod and Twig_Demon for constant feedback"
authors="bigdious"
description='''
A mod to make you smile.'''

[[dependencies.risus]]
    modId="neoforge"
	type="required"
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.risus]]
    modId="minecraft"
	type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
