modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT license"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''A mod to make you smile.'''
itemIcon="risus:smiling_remains"
enumExtensions="META-INF/enumextensions.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.risus]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.risus]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
