package com.bigdious.risus.init;

import com.bigdious.risus.Risus;
import com.bigdious.risus.blocks.*;
import com.bigdious.risus.blocks.interfaces.DecomposingBlock;
import com.bigdious.risus.blocks.interfaces.RisusWeatheringCopper;
import com.bigdious.risus.blocks.interfaces.SimpleMultiloggedBlock;
import com.bigdious.risus.blocks.plantblocks.RisusGrowingPlantBodyBlock;
import com.bigdious.risus.blocks.plantblocks.RisusGrowingPlantHeadBlock;
import com.bigdious.risus.util.RisusSkullType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Function;
import java.util.function.Supplier;

public class RisusBlocks {

	public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(Risus.MODID);

	//FAMILY TREE
	public static final BlockSetType BONDKNOT_SET = new BlockSetType(Risus.prefix("bondknot").toString());
	public static final WoodType BONDKNOT_TYPE = WoodType.register(new WoodType(Risus.prefix("bondknot").toString(), BONDKNOT_SET));
	public static final DeferredBlock<Block> CRYSTALLIZED_BONDS = registerWithItem("crystallized_bonds", CrystallizedBondsBlock::new, () -> Block.Properties.of().mapColor(MapColor.NONE).instrument(NoteBlockInstrument.HAT).noOcclusion().sound(SoundType.GLASS).strength(0.25F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<RotatedPillarBlock> BONDKNOT_LOG = registerWithItem("bondknot_log", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<RotatedPillarBlock> BONDKNOT_WOOD = registerWithItem("bondknot_wood", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<RotatedPillarBlock> POPPING_BONDKNOT_LOG = registerWithItem("popping_bondknot_log", PoppingBondknotBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<RotatedPillarBlock> POPPING_BONDKNOT_WOOD = registerWithItem("popping_bondknot_wood", PoppingBondknotBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<RotatedPillarBlock> STRIPPED_BONDKNOT_LOG = registerWithItem("stripped_bondknot_log", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<RotatedPillarBlock> STRIPPED_BONDKNOT_WOOD = registerWithItem("stripped_bondknot_wood", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<Block> BONDKNOT_PLANKS = registerWithItem("bondknot_planks", Block::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava().instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD));
	public static final DeferredBlock<StairBlock> BONDKNOT_STAIRS = registerWithItem("bondknot_stairs", properties -> new RisusStairBlock(() -> BONDKNOT_PLANKS.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()));
	public static final DeferredBlock<SlabBlock> BONDKNOT_SLAB = registerWithItem("bondknot_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()));
	public static final DeferredBlock<FenceBlock> BONDKNOT_FENCE = registerWithItem("bondknot_fence", RisusFenceBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()));
	public static final DeferredBlock<FenceGateBlock> BONDKNOT_FENCE_GATE = registerWithItem("bondknot_fence_gate", properties -> new FenceGateBlock(BONDKNOT_TYPE, properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()));
	public static final DeferredBlock<PressurePlateBlock> BONDKNOT_PRESSURE_PLATE = registerWithItem("bondknot_pressure_plate", properties -> new PressurePlateBlock(BONDKNOT_SET, properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).forceSolidOn());
	public static final DeferredBlock<ButtonBlock> BONDKNOT_BUTTON = registerWithItem("bondknot_button", properties -> new ButtonBlock(BONDKNOT_SET, 30, properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()));
	public static final DeferredBlock<TrapDoorBlock> BONDKNOT_TRAPDOOR = registerWithItem("bondknot_trapdoor", properties -> new RisusTrapDoorBlock(BONDKNOT_SET, properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).noOcclusion());
	public static final DeferredBlock<DoorBlock> BONDKNOT_DOOR = register("bondknot_door", properties -> new DoorBlock(BONDKNOT_SET, properties), () -> BONDKNOT_PLANKS.get().properties().noOcclusion());
	public static final DeferredBlock<StandingSignBlock> BONDKNOT_SIGN = register("bondknot_sign", properties -> new RisusSignBlock(properties, BONDKNOT_TYPE), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).noOcclusion().noCollission().forceSolidOn());
	public static final DeferredBlock<WallSignBlock> BONDKNOT_WALL_SIGN = register("bondknot_wall_sign", properties -> new RisusWallSignBlock(BONDKNOT_TYPE, properties), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).noOcclusion().noCollission().forceSolidOn());
	public static final DeferredBlock<CeilingHangingSignBlock> BONDKNOT_HANGING_SIGN = register("bondknot_hanging_sign", properties -> new RisusCeilingHangingSignBlock(properties, BONDKNOT_TYPE), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).noOcclusion().noCollission().forceSolidOn());
	public static final DeferredBlock<WallHangingSignBlock> BONDKNOT_WALL_HANGING_SIGN = register("bondknot_wall_hanging_sign", properties -> new RisusWallHangingSignBlock(properties, BONDKNOT_TYPE), () -> BlockBehaviour.Properties.ofFullCopy(BONDKNOT_PLANKS.get()).noOcclusion().forceSolidOn());
	public static final DeferredBlock<Block> BABY_RIBCAGE = registerWithItem("baby_ribcage", BabyRibcageBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).noOcclusion().forceSolidOn().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> RIBCAGE = registerWithItem("ribcage", RibcageBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BOND_GLASS = registerWithItem("bond_glass", RisusGlassBlock::new, () -> Block.Properties.ofFullCopy(Blocks.GLASS).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> CONTAINMENT_GLASS = registerWithItem("containment_glass", RisusGlassBlock::new, () -> Block.Properties.ofFullCopy(Blocks.GLASS).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));

	//UTILITY
	public static final DeferredBlock<Block> ALTERATION_CATALYST = registerWithFireResistantItem("alteration_catalyst", AlterationCatalystBlock::new, () -> Block.Properties.ofFullCopy(Blocks.OBSIDIAN).noOcclusion().pushReaction(PushReaction.BLOCK).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0).strength(-1.0F, 3600000.8F));
	public static final DeferredBlock<Block> ANGEL_ALTAR = registerWithFireResistantItem("angel_altar", AngelAltarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.COLOR_BLACK).noOcclusion().pushReaction(PushReaction.NORMAL).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> DEPTH_VASE = registerWithItem("depth_vase", DepthVaseBlock::new, () -> Block.Properties.ofFullCopy(Blocks.DECORATED_POT).mapColor(MapColor.NONE).pushReaction(PushReaction.DESTROY).noOcclusion().strength(2.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> LAUGHING_STALK = registerWithItem("laughing_stalk", BiomeBlock::new, () -> Block.Properties.ofFullCopy(Blocks.DECORATED_POT).mapColor(MapColor.NONE).pushReaction(PushReaction.DESTROY).noOcclusion().strength(2.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WEAVER_NEST = registerWithItem("weaver_nest", WeaverNestBlock::new, () -> Block.Properties.of().mapColor(MapColor.COLOR_RED).noOcclusion().instabreak().sound(SoundType.HONEY_BLOCK).noCollission().forceSolidOn().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> DISPLAY_NOTCH = register("display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> INVISIBLE_DISPLAY_NOTCH = register("invisible_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.NONE).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> GRAY_DISPLAY_NOTCH = register("gray_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GRAY).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> LIGHT_GRAY_DISPLAY_NOTCH = register("light_gray_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WHITE_DISPLAY_NOTCH = register("white_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.SNOW).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> RED_DISPLAY_NOTCH = register("red_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> ORANGE_DISPLAY_NOTCH = register("orange_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_ORANGE).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> YELLOW_DISPLAY_NOTCH = register("yellow_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_YELLOW).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> GREEN_DISPLAY_NOTCH = register("green_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> LIME_DISPLAY_NOTCH = register("lime_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GREEN).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BLUE_DISPLAY_NOTCH = register("blue_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLUE).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> CYAN_DISPLAY_NOTCH = register("cyan_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_CYAN).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> LIGHT_BLUE_DISPLAY_NOTCH = register("light_blue_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_BLUE).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> PURPLE_DISPLAY_NOTCH = register("purple_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> MAGENTA_DISPLAY_NOTCH = register("magenta_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_MAGENTA).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> PINK_DISPLAY_NOTCH = register("pink_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PINK).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BROWN_DISPLAY_NOTCH = register("brown_display_notch", DisplayNotchBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BROWN).strength(1.5F, 6.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> FLESHY_SPAWNER = registerWithItem("fleshy_spawner", RisusSpawnerBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SPAWNER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BLOODY_SPONGE = registerWithItem("bloody_sponge", BloodySpongeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.SPONGE));
	public static final DeferredBlock<Block> LIGHT_EXCREMENT = registerWithItem("light_excrement", LightExcrementBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OCHRE_FROGLIGHT).instabreak().lightLevel(state -> 15));
	public static final DeferredBlock<Block> RITUAL = register("ritual", RitualBlock::new, () -> BlockBehaviour.Properties.of().strength(-1.0F, 3600000.0F).pushReaction(PushReaction.BLOCK).noLootTable());

	//COPPER AMALGAM
	public static final DeferredBlock<Block> COPPER_AMALGAM = registerWithItem("copper_amalgam", properties -> new CopperAmalgamBlock(RisusWeatheringCopper.RisusWeatherState.UNAFFECTED, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.COPPER_BLOCK).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> EXPOSED_COPPER_AMALGAM = registerWithItem("exposed_copper_amalgam", properties -> new CopperAmalgamBlock(RisusWeatheringCopper.RisusWeatherState.EXPOSED, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.EXPOSED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WEATHERED_COPPER_AMALGAM = registerWithItem("weathered_copper_amalgam", properties -> new CopperAmalgamBlock(RisusWeatheringCopper.RisusWeatherState.WEATHERED, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WEATHERED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> OXIDIZED_COPPER_AMALGAM = registerWithItem("oxidized_copper_amalgam", properties -> new CopperAmalgamBlock(RisusWeatheringCopper.RisusWeatherState.OXIDIZED, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OXIDIZED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WAXED_COPPER_AMALGAM = registerWithItem("waxed_copper_amalgam", MultiloggedRotateableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.COPPER_BLOCK).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WAXED_EXPOSED_COPPER_AMALGAM = registerWithItem("waxed_exposed_copper_amalgam", MultiloggedRotateableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.EXPOSED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WAXED_WEATHERED_COPPER_AMALGAM = registerWithItem("waxed_weathered_copper_amalgam", MultiloggedRotateableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WEATHERED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> WAXED_OXIDIZED_COPPER_AMALGAM = registerWithItem("waxed_oxidized_copper_amalgam", MultiloggedRotateableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.OXIDIZED_COPPER).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));

	//MAW STUFF
	public static final DeferredBlock<Block> MAW_GUTS = registerWithItem("maw_guts", MawGutsBlock::new, () -> Block.Properties.of().mapColor(MapColor.NONE).pushReaction(PushReaction.DESTROY).noOcclusion().requiresCorrectToolForDrops().strength(4.0F).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> MIRAGE_GRASS_BLOCK = registerWithItem("mirage_grass_block", properties -> new MirageBlock(properties, Blocks.GRASS_BLOCK), () -> Block.Properties.ofFullCopy(Blocks.GRASS_BLOCK).noOcclusion().forceSolidOn().mapColor(MapColor.NONE));
	public static final DeferredBlock<Block> MIRAGE_SAND = registerWithItem("mirage_sand", properties -> new MirageBlock(properties, Blocks.SAND), () -> Block.Properties.ofFullCopy(Blocks.SAND).noOcclusion().forceSolidOn().mapColor(MapColor.NONE));
	public static final DeferredBlock<Block> MIRAGE_END_STONE = registerWithItem("mirage_end_stone", properties -> new MirageBlock(properties, Blocks.END_STONE), () -> Block.Properties.ofFullCopy(Blocks.END_STONE).noOcclusion().forceSolidOn().mapColor(MapColor.NONE));
	public static final DeferredBlock<Block> MIRAGE_NETHERRACK = registerWithItem("mirage_netherrack", properties -> new MirageBlock(properties, Blocks.NETHERRACK), () -> Block.Properties.ofFullCopy(Blocks.NETHERRACK).noOcclusion().forceSolidOn().mapColor(MapColor.NONE));
	public static final DeferredBlock<Block> GLUTTONY_SCALEPLATE = registerWithFireResistantItem("gluttony_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> IMITATION_SCALEPLATE = registerWithFireResistantItem("imitation_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> FLOWERING_IMITATION_SCALEPLATE = registerWithFireResistantItem("flowering_imitation_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BUDDING_IMITATION_SCALEPLATE = registerWithFireResistantItem("budding_imitation_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> FLATTENED_SCALES_BLOCK = registerWithFireResistantItem("flattened_scales_block", ActuallyUseableDirectionalBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS));
	public static final DeferredBlock<Block> FLATTENED_IMITATION_SCALES_BLOCK = registerWithFireResistantItem("flattened_imitation_scales_block", ActuallyUseableDirectionalBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS));
	public static final DeferredBlock<StairBlock> IMITATION_SCALES_BLOCK_STAIRS = registerWithFireResistantItem("imitation_scales_block_stairs", properties -> new RisusStairBlock(() -> FLATTENED_IMITATION_SCALES_BLOCK.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<SlabBlock> IMITATION_SCALES_BLOCK_SLAB = registerWithFireResistantItem("imitation_scales_block_slab",  RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<RisusWallBlock> IMITATION_SCALES_BLOCK_WALL = registerWithFireResistantItem("imitation_scales_block_wall",  RisusWallBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<Block> UNALLOYED_SCALES_BLOCK = registerWithFireResistantItemWithoutRarity("unalloyed_scales_block", ActuallyUseableDirectionalBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS));
	public static final DeferredBlock<StairBlock> UNALLOYED_SCALES_BLOCK_STAIRS = registerWithFireResistantItemWithoutRarity("unalloyed_scales_block_stairs", properties -> new RisusStairBlock(() -> FLATTENED_IMITATION_SCALES_BLOCK.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<SlabBlock> UNALLOYED_SCALES_BLOCK_SLAB = registerWithFireResistantItemWithoutRarity("unalloyed_scales_block_slab",  RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<RisusWallBlock> UNALLOYED_SCALES_BLOCK_WALL = registerWithFireResistantItemWithoutRarity("unalloyed_scales_block_wall",  RisusWallBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(FLATTENED_IMITATION_SCALES_BLOCK.get()));
	public static final DeferredBlock<Block> UNALLOYED_SCALEPLATE = registerWithFireResistantItemWithoutRarity("unalloyed_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> FLOWERING_UNALLOYED_SCALEPLATE = registerWithFireResistantItemWithoutRarity("flowering_unalloyed_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BUDDING_UNALLOYED_SCALEPLATE = registerWithFireResistantItemWithoutRarity("budding_unalloyed_scaleplate", ScaleplateBlock::new, () -> Block.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));

	//REMAINS
	public static final DeferredBlock<Block> ASHEN_REMAINS = registerWithItem("ashen_remains", RemainsBlock::new, () -> Block.Properties.ofFullCopy(Blocks.SOUL_SOIL).mapColor(MapColor.COLOR_BLACK));
	public static final DeferredBlock<Block> SMILING_REMAINS = registerWithItem("smiling_remains", RemainsBlock::new, () -> Block.Properties.ofFullCopy(Blocks.NETHERRACK).mapColor(MapColor.COLOR_BLACK));
	public static final DeferredBlock<MultifaceBlock> SPREADING_REMAINS = registerWithItem("spreading_remains", SpreadingRemainsBlock::new, () -> Block.Properties.ofFullCopy(Blocks.SCULK_VEIN).mapColor(MapColor.COLOR_BLACK).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> ORGANIC_MATTER_BLOCK = registerWithItem("organic_matter_block", OrganicMatterBlock::new, () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK).noOcclusion());
	public static final DeferredBlock<Block> ASHEN_SPIRE = registerWithItem("ashen_spire", AshenSpireBlock::new, () -> Block.Properties.ofFullCopy(RisusBlocks.ASHEN_REMAINS.get()).mapColor(MapColor.COLOR_BLACK).noCollission().sound(SoundType.TWISTING_VINES).offsetType(BlockBehaviour.OffsetType.XZ).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : state.getValue(AshenSpireBlock.LanternEnum.LANTERN) == AshenSpireBlock.LanternEnum.FIRE ? 15 : state.getValue(AshenSpireBlock.LanternEnum.LANTERN) == AshenSpireBlock.LanternEnum.SOUL ? 10 : state.getValue(AshenSpireBlock.LanternEnum.LANTERN) == AshenSpireBlock.LanternEnum.CINDERGLEE ? 5 : 0));

	//MISC FULLBLOCK
	public static final DeferredBlock<Block> LAUGHING_OBSIDIAN = registerWithItem("laughing_obsidian", LaughingObsidianBlock::new, () -> Block.Properties.ofFullCopy(Blocks.CRYING_OBSIDIAN));
	public static final DeferredBlock<RotatedPillarBlock> ENGRAVED_BASALT = registerWithItem("engraved_basalt", LoggingPillarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.POLISHED_BASALT).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> BURNT_HYPHAE = registerWithItem("burnt_hyphae", Block::new, () -> Block.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE));
	public static final DeferredBlock<Block> SCAB = registerWithItem("scab", Block::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STRIPPED_WARPED_HYPHAE).mapColor(MapColor.COLOR_BROWN).instrument(NoteBlockInstrument.SNARE).strength(3.0F, 3.0F).sound(SoundType.NETHER_WOOD).requiresCorrectToolForDrops());
	public static final DeferredBlock<Block> COAGULATED_BLOOD_BLOCK = registerWithItem("coagulated_blood_block", Block::new, () -> Block.Properties.of().mapColor(MapColor.COLOR_RED).instabreak().sound(SoundType.HONEY_BLOCK).forceSolidOn());
	public static final DeferredBlock<Block> DARKNESS = register("darkness", DarknessBlock::new, () -> BlockBehaviour.Properties.of().noOcclusion().pushReaction(PushReaction.DESTROY).instabreak().replaceable());
	public static final DeferredBlock<Block> FADING_SHADOW = register("fading_shadow", FadingShadowBlock::new, () -> BlockBehaviour.Properties.of().noOcclusion().pushReaction(PushReaction.DESTROY).instabreak().replaceable());

	//NONFULLBLOCK DECO
	public static final DeferredBlock<Block> BIG_CHAIN = registerWithItem("big_chain", BigChainBlock::new, () -> Block.Properties.ofFullCopy(Blocks.CHAIN).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> ZIT = registerWithItem("zit", ZitBlock::new, () -> Block.Properties.ofFullCopy(Blocks.SCULK).noCollission().noOcclusion().forceSolidOn().instabreak());
	public static final DeferredBlock<Block> BLOODWEAVE = registerWithItem("bloodweave", BloodweaveBlock::new, () -> Block.Properties.of().mapColor(MapColor.COLOR_RED).noOcclusion().instabreak().sound(SoundType.HONEY_BLOCK).noCollission().forceSolidOn());
	public static final DeferredBlock<Block> BLOODWYRM_HEAD = register("bloodwyrm_head", properties -> new RisusSkullBlock(RisusSkullType.BLOODWYRM, properties), () -> Block.Properties.ofFullCopy(Blocks.DRAGON_HEAD).instabreak());
	public static final DeferredBlock<Block> BLOODWYRM_WALL_HEAD = register("bloodwyrm_wall_head", properties -> new RisusWallSkullBlock(RisusSkullType.BLOODWYRM, properties), () -> Block.Properties.ofFullCopy(Blocks.DRAGON_WALL_HEAD).instabreak());
	public static final DeferredBlock<Block> INACTIVE_HOLDER = registerWithItem("inactive_holder", InactiveHolderBlock::new, () -> Block.Properties.ofFullCopy(RisusBlocks.ASHEN_REMAINS.get()).noOcclusion());


	//PLANTS
	//yes, teeth are plants
	public static final DeferredBlock<MultifaceBlock> TEETH = registerWithItem("teeth", SpreadingRemainsBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).noOcclusion().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<Block> HEART_TRANSPLANT = registerWithItem("heart_transplant", HeartTransplantBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).pushReaction(PushReaction.DESTROY).noCollission().instabreak().forceSolidOn().sound(SoundType.SCULK).offsetType(BlockBehaviour.OffsetType.XZ));
	public static final DeferredBlock<Block> REGEN_ROSE = registerWithItemWithoutRarity("regen_rose", RegenRoseBlock::new, () -> BlockBehaviour.Properties.of().mapColor(MapColor.PLANT).pushReaction(PushReaction.DESTROY).noCollission().instabreak().sound(SoundType.BIG_DRIPLEAF).offsetType(BlockBehaviour.OffsetType.XZ));
	public static final DeferredBlock<Block> POTTED_HEART_TRANSPLANT = register("potted_heart_transplant", properties -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, HEART_TRANSPLANT, properties), () -> BlockBehaviour.Properties.of().mapColor(MapColor.NONE).pushReaction(PushReaction.DESTROY).instabreak().noOcclusion());
	public static final DeferredBlock<Block> POTTED_REGEN_ROSE = register("potted_regen_rose", properties -> new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT, REGEN_ROSE, properties), () -> BlockBehaviour.Properties.of().mapColor(MapColor.NONE).pushReaction(PushReaction.DESTROY).instabreak().noOcclusion());
	public static final DeferredBlock<RisusGrowingPlantBodyBlock> NEURON_STEM = register("neuron", NeuronStemBlock::new, () -> Block.Properties.ofFullCopy(Blocks.TWISTING_VINES_PLANT).mapColor(MapColor.SAND).offsetType(BlockBehaviour.OffsetType.XZ).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<RisusGrowingPlantHeadBlock> NEURON_HEAD = registerWithItem("neuron_head", NeuronHeadBlock::new, () -> Block.Properties.ofFullCopy(Blocks.TWISTING_VINES).mapColor(MapColor.SAND).offsetType(BlockBehaviour.OffsetType.XZ).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<RisusGrowingPlantBodyBlock> VEINS = register("veins", VeinsBlock::new, () -> Block.Properties.ofFullCopy(Blocks.WEEPING_VINES).offsetType(BlockBehaviour.OffsetType.XZ).mapColor(MapColor.COLOR_RED).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<RisusGrowingPlantHeadBlock> VEINS_END = register("veins_end", VeinsEndBlock::new, () -> Block.Properties.ofFullCopy(Blocks.WEEPING_VINES).offsetType(BlockBehaviour.OffsetType.XZ).mapColor(MapColor.COLOR_RED).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));

	//GRIMSTONE
	public static final DeferredBlock<RotatedPillarBlock> GRIMSTONE = registerWithItem("grimstone", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).mapColor(MapColor.COLOR_GRAY));
	public static final DeferredBlock<Block> ACTIVE_GRIMSTONE = registerWithItem("active_grimstone", Block::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<Block> GRIMSTONE_BRICKS = registerWithItem("grimstone_bricks", Block::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<Block> CRACKED_GRIMSTONE_BRICKS = registerWithItem("cracked_grimstone_bricks", Block::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<SlabBlock> GRIMSTONE_SLAB = registerWithItem("grimstone_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<SlabBlock> GRIMSTONE_BRICKS_SLAB = registerWithItem("grimstone_bricks_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<SlabBlock> POLISHED_GRIMSTONE_SLAB = registerWithItem("polished_grimstone_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<StairBlock> GRIMSTONE_BRICKS_STAIRS = registerWithItem("grimstone_bricks_stairs", properties -> new RisusStairBlock(() -> GRIMSTONE_BRICKS.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<StairBlock> GRIMSTONE_STAIRS = registerWithItem("grimstone_stairs", properties -> new RisusStairBlock(() -> GRIMSTONE.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<StairBlock> POLISHED_GRIMSTONE_STAIRS = registerWithItem("polished_grimstone_stairs", properties -> new RisusStairBlock(() -> GRIMSTONE.get().defaultBlockState(), properties), () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<RisusWallBlock> GRIMSTONE_WALL = registerWithItem("grimstone_wall", RisusWallBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<RisusWallBlock> GRIMSTONE_BRICKS_WALL = registerWithItem("grimstone_bricks_wall", RisusWallBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<RisusWallBlock> POLISHED_GRIMSTONE_WALL = registerWithItem("polished_grimstone_wall", RisusWallBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<Block> POLISHED_GRIMSTONE = registerWithItem("polished_grimstone", Block::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));
	public static final DeferredBlock<Block> CHISELED_GRIMSTONE = registerWithItem("chiseled_grimstone", BaseRotatableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(GRIMSTONE.get()));

	//TISSUE, BONE, SKIN, EYES AND HAIR
	public static final DeferredBlock<DecomposingTissueBlock> TISSUE = registerWithItem("tissue", properties -> new DecomposingTissueBlock(DecomposingBlock.DecomposeState.NONE, properties), () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<StairBlock> TISSUE_STAIRS = registerWithItem("tissue_stairs", properties -> new RisusStairBlock(() -> TISSUE.get().defaultBlockState(), properties), () -> Block.Properties.ofFullCopy(RisusBlocks.TISSUE.get()));
	public static final DeferredBlock<SlabBlock> TISSUE_SLAB = registerWithItem("tissue_slab", RisusSlabBlock::new, () -> Block.Properties.ofFullCopy(RisusBlocks.TISSUE.get()));
	public static final DeferredBlock<RisusWallBlock> TISSUE_WALL = registerWithItem("tissue_wall", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(RisusBlocks.TISSUE.get()));
	public static final DeferredBlock<RisusWallBlock> ROTTING_TISSUE = registerWithItem("rotting_tissue", properties -> new DecomposingTissueBlock(DecomposingBlock.DecomposeState.ROTTING, properties), () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RisusWallBlock> DECOMPOSING_TISSUE = registerWithItem("decomposing_tissue", properties -> new DecomposingTissueBlock(DecomposingBlock.DecomposeState.DECOMPOSING, properties), () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RisusWallBlock> DECAYING_TISSUE = registerWithItem("decaying_tissue", properties -> new DecomposingTissueBlock(DecomposingBlock.DecomposeState.DECAYING, properties), () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RotatedPillarBlock> FULL_BONE_BLOCK = registerWithItem("full_bone_block", RotatedPillarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK));
	public static final DeferredBlock<StairBlock> FULL_BONE_STAIRS = registerWithItem("full_bone_stairs", properties -> new RisusStairBlock(Blocks.BONE_BLOCK::defaultBlockState, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK));
	public static final DeferredBlock<SlabBlock> FULL_BONE_SLAB = registerWithItem("full_bone_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FULL_BONE_BLOCK.get()));
	public static final DeferredBlock<RisusWallBlock> BONE_WALL = registerWithItem("bone_wall", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK));
	public static final DeferredBlock<StairBlock> BONE_STAIRS = registerWithItem("bone_stairs", properties -> new RisusStairBlock(Blocks.BONE_BLOCK::defaultBlockState, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK));
	public static final DeferredBlock<SlabBlock> BONE_SLAB = registerWithItem("bone_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK));
	public static final DeferredBlock<RotatedPillarBlock> FOSSIL = registerWithItem("fossil", RotatedPillarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<StairBlock> FOSSIL_STAIRS = registerWithItem("fossil_stairs", properties -> new RisusStairBlock(Blocks.BONE_BLOCK::defaultBlockState, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<SlabBlock> FOSSIL_SLAB = registerWithItem("fossil_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FULL_BONE_BLOCK.get()).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<RisusWallBlock> FOSSIL_WALL = registerWithItem("fossil_wall", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<RotatedPillarBlock> FULL_FOSSIL = registerWithItem("full_fossil", RotatedPillarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<StairBlock> FULL_FOSSIL_STAIRS = registerWithItem("full_fossil_stairs", properties -> new RisusStairBlock(Blocks.BONE_BLOCK::defaultBlockState, properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<SlabBlock> FULL_FOSSIL_SLAB = registerWithItem("full_fossil_slab", RisusSlabBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BONE_BLOCK).mapColor(MapColor.RAW_IRON));
	public static final DeferredBlock<Block> LIVING_TISSUE = registerWithItem("living_tissue", Block::new, () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RisusWallBlock> ROTTED_TISSUE = registerWithItem("rotted_tissue", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RisusWallBlock> DECOMPOSED_TISSUE = registerWithItem("decomposed_tissue", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<RisusWallBlock> DECAYED_TISSUE = registerWithItem("decayed_tissue", RisusWallBlock::new, () -> Block.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_ENDER = registerWithItem("eye_ender", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_BLEACHED = registerWithItem("eye_bleached", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_BLOODSHOT = registerWithItem("eye_bloodshot", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_EMERALD = registerWithItem("eye_emerald", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_GOLDEN = registerWithItem("eye_golden", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_ENDER_GLOWING = registerWithItem("eye_ender_glowing", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_BLEACHED_GLOWING = registerWithItem("eye_bleached_glowing", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_BLOODSHOT_GLOWING = registerWithItem("eye_bloodshot_glowing", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_EMERALD_GLOWING = registerWithItem("eye_emerald_glowing", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> EYE_GOLDEN_GLOWING = registerWithItem("eye_golden_glowing", EquipableEyeBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.NETHER_WART_BLOCK));
	public static final DeferredBlock<Block> FLESHY_SKIN = registerWithItem("fleshy_skin", FleshySkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.TISSUE.get()).mapColor(MapColor.TERRACOTTA_WHITE));
	public static final DeferredBlock<Block> CURVED_FLESHY_SKIN = registerWithItem("curved_fleshy_skin", CurvedSkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FLESHY_SKIN.get()));
	public static final DeferredBlock<Block> SKIN = registerWithItem("skin", SkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FLESHY_SKIN.get()));
	public static final DeferredBlock<Block> HAIRY_FLESHY_SKIN = registerWithItem("hairy_fleshy_skin", HairyFleshySkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FLESHY_SKIN.get()));
	public static final DeferredBlock<Block> HAIRY_CURVED_FLESHY_SKIN = registerWithItem("hairy_curved_fleshy_skin", HairyCurvedSkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FLESHY_SKIN.get()));
	public static final DeferredBlock<Block> HAIRY_SKIN = registerWithItem("hairy_skin", HairySkinBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(RisusBlocks.FLESHY_SKIN.get()));
	public static final DeferredBlock<Block> TALL_HAIR = registerWithItem("tall_hair", RisusTallGrassBlock::new, () -> Block.Properties.ofFullCopy(Blocks.TALL_GRASS).mapColor(MapColor.COLOR_LIGHT_GRAY).offsetType(BlockBehaviour.OffsetType.XYZ).lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 0));
	public static final DeferredBlock<RotatedPillarBlock> BUNDLE_OF_HAIR = registerWithItem("bundle_of_hair", RotatedPillarBlock::new, () -> Block.Properties.ofFullCopy(Blocks.DRIED_KELP_BLOCK).mapColor(MapColor.COLOR_LIGHT_GRAY).ignitedByLava());

	//CINDERGLEE
	public static final DeferredBlock<Block> JOYFLAME_TORCH = register("joyflame_torch", ModdedTorchBlock::new, () -> Block.Properties.ofFullCopy(Blocks.TORCH).forceSolidOn().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 5));
	public static final DeferredBlock<Block> JOYFLAME_WALL_TORCH = register("joyflame_wall_torch", ModdedWallTorchBlock::new, () -> Block.Properties.ofFullCopy(Blocks.TORCH).forceSolidOn().lightLevel(state -> state.getValue(SimpleMultiloggedBlock.MultiloggingEnum.FLUIDLOGGED) == SimpleMultiloggedBlock.MultiloggingEnum.LAVA ? 15 : 5));
	public static final DeferredBlock<Block> JOYFLAME_CAMPFIRE = registerWithItem("joyflame_campfire", properties -> new RisusCampfireBlock(false, 2, properties), () -> Block.Properties.ofFullCopy(Blocks.CAMPFIRE));
	public static final DeferredBlock<Block> JOYFLAME_LANTERN = registerWithItem("joyflame_lantern", LanternBlock::new, () -> Block.Properties.ofFullCopy(Blocks.LANTERN).lightLevel(state -> 5));
	public static final DeferredBlock<Block> JOYFLAME_FIRE = register("joyflame_fire", JoyflameFireBlock::new, () -> Block.Properties.ofFullCopy(Blocks.FIRE).lightLevel(state -> 5));
	public static final DeferredBlock<Block> CURVED_RITUAL_BLOCK = registerWithItem("curved_ritual_block", BaseRotatableBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_GLAZED_TERRACOTTA));
	public static final DeferredBlock<Block> LINEAR_RITUAL_BLOCK = registerWithItem("linear_ritual_block", RotatedPillarBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_GLAZED_TERRACOTTA));

	//FLUIDSTUFF
	public static final DeferredBlock<LiquidBlock> BLOOD_FLUID_BLOCK = register("blood_fluid_block", properties -> new BloodFluidBlock(RisusFluids.SOURCE_BLOOD.get(), properties), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WATER).mapColor(MapColor.COLOR_RED));
	public static final DeferredBlock<Block> BLOOD_CAULDRON = register("blood_cauldron", BloodCauldronBlock::new, () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CAULDRON));

	public static <T extends Block> DeferredBlock<T> register(String name, Function<BlockBehaviour.Properties, T> block, Supplier<BlockBehaviour.Properties> properties) {
		return BLOCKS.register(name, () -> block.apply(properties.get()));
	}

	public static <T extends Block> DeferredBlock<T> registerWithItem(String name, Function<BlockBehaviour.Properties, T> block, Supplier<BlockBehaviour.Properties> properties) {
		DeferredBlock<T> ret = BLOCKS.register(name, () -> block.apply(properties.get()));
		RisusItems.register(name, itemProps -> new BlockItem(ret.get(), itemProps), () -> new Item.Properties().rarity(RisusItems.BLOOD));
		return ret;
	}
	public static <T extends Block> DeferredBlock<T> registerWithFireResistantItem(String name, Function<BlockBehaviour.Properties, T> block, Supplier<BlockBehaviour.Properties> properties) {
		DeferredBlock<T> ret = BLOCKS.register(name, () -> block.apply(properties.get()));
		RisusItems.register(name, itemProps -> new BlockItem(ret.get(), itemProps), () -> new Item.Properties().fireResistant().rarity(RisusItems.BLOOD));
		return ret;
	}
	public static <T extends Block> DeferredBlock<T> registerWithItemWithoutRarity(String name, Function<BlockBehaviour.Properties, T> block, Supplier<BlockBehaviour.Properties> properties) {
		DeferredBlock<T> ret = BLOCKS.register(name, () -> block.apply(properties.get()));
		RisusItems.register(name, itemProps -> new BlockItem(ret.get(), itemProps), Item.Properties::new);
		return ret;
	}
	public static <T extends Block> DeferredBlock<T> registerWithFireResistantItemWithoutRarity(String name, Function<BlockBehaviour.Properties, T> block, Supplier<BlockBehaviour.Properties> properties) {
		DeferredBlock<T> ret = BLOCKS.register(name, () -> block.apply(properties.get()));
		RisusItems.register(name, itemProps -> new BlockItem(ret.get(), itemProps), () -> new Item.Properties().fireResistant());
		return ret;
	}

}
